### PR TITLE
[test] Replace zuul with sauce-test

### PR DESCRIPTION
**Pull request by lpinca**
sauce-test does not require a tunnel to localhost. It browserifies the tests, uploads them to http://tempjs.org/ and then uses the WebDriver API to navigate to the given location and determine if tests passed or failed.

Currently this is more reliable than zuul + localtunnel.me so I think it makes sense to switch.

### CODE REVIEW

**Comment by 3rd-Eden** [comment]
Utill tempjs.org is pulled offline. It makes me wonder if we couldn't just automatically upload the browserified bundle to a `gh-pages` branch and have WD API navigate to that.

**Comment by 3rd-Eden** [comment]
Utill tempjs.org is pulled offline. It makes me wonder if we couldn't just automatically upload the browserified bundle to a `gh-pages` branch and have WD API navigate to that.

**Comment by lpinca** [comment]
> Utill tempjs.org is pulled offline.

Yes I also thought about that but localtunnel.me can also be dismissed. I think it's possible to use something like gh-pages but some work has to be done in https://github.com/ForbesLindesay/sauce-test.

**Comment by lpinca** [comment]
Reverting to `zuul` should be easy if this proves to be a wrong move.

**Pull request merged**
