### PR TITLE
update tests, and add contra.emitter

### PR DESCRIPTION
**Pull request by mikekidder**
I initially updated the benchmark tests to compare a new event emitter, **contra.emitter**.  

However, I also updated benchmarks to compare **eventemitter3@0.6.1** to latest **eventemitter3@master**.  The results may surprise you.

See my comment regarding the preliminary results on running `emit.js` - https://github.com/goatslacker/alt/pull/231

### CODE REVIEW

**Comment by lpinca** [comment]
LGTM.
I'm also not even that much surprised about the new performances.
The prefixed events and the features we added have a serious impact.

**Comment by 3rd-Eden** [comment]
Agreed with @lpinca, I know that the recent versions of EE3 are slower then the one I first build but that's with a reason as the old versions had some serious and dangerous bugs.

**Comment by lpinca** [comment]
Just for reference, `run/emit.js` against current master:
```
 log:      Finished benchmarking: "EventEmitter1"
 metric:   Count (97592), Cycles (8), Elapsed (5.515), Hz (1145538.0258039199)
 log:      Finished benchmarking: "EventEmitter2"
 metric:   Count (113408), Cycles (5), Elapsed (5.428), Hz (2212898.385670548)
 log:      Finished benchmarking: "EventEmitter3@0.6.1"
 metric:   Count (165950), Cycles (8), Elapsed (5.55), Hz (3203953.8669362618)
 log:      Finished benchmarking: "EventEmitter3(master)"
 metric:   Count (82420), Cycles (9), Elapsed (5.583), Hz (1616367.9669747844)
 log:      Finished benchmarking: "Drip"
 metric:   Count (135018), Cycles (6), Elapsed (5.476), Hz (2628369.431169615)
 log:      Finished benchmarking: "fastemitter"
 metric:   Count (220875), Cycles (8), Elapsed (5.532), Hz (4363327.701575962)
 log:      Finished benchmarking: "event-emitter"
 metric:   Count (77882), Cycles (8), Elapsed (5.558), Hz (1515282.8128886493)
 log:      Finished benchmarking: "contra.emitter"
 metric:   Count (3962), Cycles (6), Elapsed (5.479), Hz (76986.41163708303)
 info:     Benchmark: "fastemitter" is the fastest.
```
`run/emit.js` against current master with prefixed events only (no Symbols support):
```
 log:      Finished benchmarking: "EventEmitter1"
 metric:   Count (97897), Cycles (5), Elapsed (5.596), Hz (1188475.5217907464)
 log:      Finished benchmarking: "EventEmitter2"
 metric:   Count (112999), Cycles (5), Elapsed (5.531), Hz (2208603.1123529864)
 log:      Finished benchmarking: "EventEmitter3@0.6.1"
 metric:   Count (162716), Cycles (8), Elapsed (5.529), Hz (3141144.0637343777)
 log:      Finished benchmarking: "EventEmitter3(master)"
 metric:   Count (82527), Cycles (5), Elapsed (5.462), Hz (1580820.4443661068)
 log:      Finished benchmarking: "Drip"
 metric:   Count (135672), Cycles (5), Elapsed (5.696), Hz (2638332.169642573)
 log:      Finished benchmarking: "fastemitter"
 metric:   Count (230331), Cycles (7), Elapsed (5.455), Hz (4515118.688979165)
 log:      Finished benchmarking: "event-emitter"
 metric:   Count (76560), Cycles (5), Elapsed (5.499), Hz (1503983.633131721)
 log:      Finished benchmarking: "contra.emitter"
 metric:   Count (4216), Cycles (4), Elapsed (5.356), Hz (81696.77327237511)
 info:     Benchmark: "fastemitter" is the fastest.
```
`run/emit.js` against current master without prefixed events and without Symbols support:
```
log:      Finished benchmarking: "EventEmitter1"
 metric:   Count (96928), Cycles (6), Elapsed (5.516), Hz (1109657.874270942)
 log:      Finished benchmarking: "EventEmitter2"
 metric:   Count (113424), Cycles (5), Elapsed (5.453), Hz (2228898.7034504274)
 log:      Finished benchmarking: "EventEmitter3@0.6.1"
 metric:   Count (163015), Cycles (6), Elapsed (5.441), Hz (3183811.431733821)
 log:      Finished benchmarking: "EventEmitter3(master)"
 metric:   Count (162431), Cycles (8), Elapsed (5.547), Hz (3133480.5256830165)
 log:      Finished benchmarking: "Drip"
 metric:   Count (134327), Cycles (6), Elapsed (5.441), Hz (2600417.062846047)
 log:      Finished benchmarking: "fastemitter"
 metric:   Count (230678), Cycles (5), Elapsed (5.435), Hz (4550799.87346297)
 log:      Finished benchmarking: "event-emitter"
 metric:   Count (76685), Cycles (6), Elapsed (5.616), Hz (1504227.4288447506)
 log:      Finished benchmarking: "contra.emitter"
 metric:   Count (4165), Cycles (6), Elapsed (5.512), Hz (81380.84589530977)
 info:     Benchmark: "fastemitter" is the fastest.
```
As expected prefixing events has a big impact but it is necessary to not override built-in properties.

**Comment by 3rd-Eden** [comment]
The only way to remove prefixing (which prevents dictionary attacks) is use [Map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map) or WeakMap's instead. But the browser support for that is still severely lacking.

**Comment by lpinca** [comment]
Maybe we can detect if `Object.create()` is available and prefix the events only when it is not supported. If we do this the performance penalties will only affect older browsers.

**Comment by 3rd-Eden** [comment]
You can still set `toString` and `__proto__` on these objects.

**Comment by lpinca** [comment]
I'm not sure I understand this, where is the problem?
```js
> var o = Object.create(null);
undefined
> o.__proto__
undefined
> o.toString
undefined
```

**Pull request merged**
