### PR TITLE
Added Emittery to benchmarks

### PR DESCRIPTION
**Pull request by KeyboardRage**
This PR adds [Emittery](https://www.npmjs.com/package/emittery) to the benchmarks.

Some minor modifications had to be done in order to support importing ESM module, which was done by wrapping an async IIFE around the tests.

There was one other problem too though: `package.json` never had `events` listed in the packages for  `EventEmitter1`, so the tests would always throw an error. This was also added, along with the Emittery dependency.

Not sure if test results will be generated by an automated workflow, but I have noted down the results of the benchmarks if needed.

### CODE REVIEW

**Comment by KeyboardRage** [comment]
I see now that `events` was probably meant to be the built-in EventEmitter from NodeJS, but it still errored out when trying to require it.   

I can imagine this is because the version of node I used (_version 17.3.0_) require the native prefix (`node:`)? Not sure, never encountered this problem before, but will make the change to remove `events` and instead have it use `node:events` instead.

**Comment by KeyboardRage** [comment]
```
EventEmitter1 x 11,942,420 ops/sec ±1.04% (89 runs sampled)
EventEmitter3@0.1.6 x 11,727,259 ops/sec ±1.03% (90 runs sampled)
EventEmitter3(master) x 11,120,137 ops/sec ±1.08% (84 runs sampled)
fastemitter x 4,691,488 ops/sec ±1.46% (87 runs sampled)
Emittery:
Fastest is [ 'EventEmitter1' ]
```

There's also no results for `Emittery` in the `listeners.js` benchmark. Not sure why, I'm not even sure what the test is here. Just retrieving the listeners? From what I could tell `Emittery` stores them in a set instead of an array. It exposes a method to get the count of listeners, but couldn't find any documentation on returning a list of listeners. 

However, it does how an internal method that I tried using `getListeners`, which _should_ return a set of event listeners for a given event name?

**Comment by lpinca** [comment]
Thanks but I am not very happy to add it. Emittery is an _async_ event emitter. Its scope is different.

**Comment by Morglod** [comment]
According to my benchmarks its too slow comparing to "non-async"

**Comment by lpinca** [comment]
I'm closing this. Thank you anyway.

**Pull request closed without merging**
