### PR TITLE
Breaking changes

### PR DESCRIPTION
**Pull request by lpinca**
- Add `EventEmitter.prototype.listenerCount()`.
- Remove the existence checking functionality from `EventEmitter.prototype.listeners()`.
- Throw if the second argument of `EventEmitter.prototype.on()` is not a function.
- Remove `EventEmitter.prototype.setMaxListeners()`.
- Remove `bower.json` and `component.json`.

### CODE REVIEW

**Comment by lpinca** [comment]
@3rd-Eden are you ok with this? Should we add `EventEmitter.prototype.prependListener()` and `EventEmitter.prototype.prependOnceListener()`?

**Comment by 3rd-Eden** [comment]
If we want to support the latest node. We should probably add support for those API's, but we don't need to support setMaxListeners as that was only to prevent possible memory leaks. But I think having an empty function for that is still a good idea because it means we're still API compatible.

**Comment by lpinca** [comment]
I think that if we keep `setMaxListeners` we should also add `getMaxListeners` and I'm not sure what it should return.

**Comment by 3rd-Eden** [comment]
@lpinca Well, fuck it. Lets just keep it out for now as we're doing a major release anyways. If there are community members that are using this with `setMaxListeners` then we can discuss it there further.

**Comment by lpinca** [comment]
Ok, if there are no objections I'll merge this and release a new version tomorrow.

**Comment by 3rd-Eden** [comment]
Yep sounds good

**Comment by tchon** [comment]
Can we run the micro-benchmarks again to see that the ops/sec is maintained? Great work and thank you for the awesome library.

**Comment by lpinca** [comment]
I've just remembered that our `EventEmitter#emit()` is copyless so `EventEmitter#prependListener()` and `EventEmitter#prependOnceListener()` don't work with the current implementation.

```js
const EventEmitter = require('.');
const assert = require('assert');

const ee = new EventEmitter();

let count = 0;
ee.on('foo', () => {
  assert.strictEqual(++count, 1);
  ee.prependListener('foo', () => {});
});

ee.on('foo', () => {});

ee.emit('foo');
```

We should treat `EventEmitter#prependListener()`and `EventEmitter#prependOnceListener()` differently and copy the array of listeners every time they are used or change `EventEmitter#emit()`.

It's probably better to not include them for now.

**Comment by lpinca** [comment]
@tchon 

```
Starting benchmark listeners.js

EventEmitter1 x 7,572,173 ops/sec ±0.93% (92 runs sampled)
EventEmitter3@0.1.6 x 7,990,937 ops/sec ±0.31% (93 runs sampled)
EventEmitter3(master) x 8,140,661 ops/sec ±0.44% (91 runs sampled)
fastemitter x 5,554,014 ops/sec ±0.37% (88 runs sampled)
Fastest is EventEmitter3(master)

Starting benchmark init.js

EventEmitter1 x 15,101,015 ops/sec ±1.66% (89 runs sampled)
EventEmitter2 x 23,365,046 ops/sec ±0.50% (90 runs sampled)
EventEmitter3@0.1.6 x 32,657,186 ops/sec ±0.61% (88 runs sampled)
EventEmitter3(master) x 28,325,527 ops/sec ±0.25% (95 runs sampled)
Drip x 33,751,683 ops/sec ±1.31% (84 runs sampled)
fastemitter x 11,738,645 ops/sec ±0.35% (86 runs sampled)
event-emitter x 22,670,613 ops/sec ±0.23% (95 runs sampled)
contra/emitter x 1,102,480 ops/sec ±0.43% (91 runs sampled)
Fastest is Drip

Starting benchmark remove-emit.js

EventEmitter1 x 6,175,136 ops/sec ±0.44% (90 runs sampled)
EventEmitter2 x 5,767,426 ops/sec ±1.08% (87 runs sampled)
EventEmitter3@0.1.6 x 10,269,081 ops/sec ±0.91% (88 runs sampled)
EventEmitter3(master) x 11,549,113 ops/sec ±0.67% (88 runs sampled)
Drip x 5,795,926 ops/sec ±1.20% (88 runs sampled)
event-emitter x 4,515,241 ops/sec ±0.47% (90 runs sampled)
contra/emitter x 403,089 ops/sec ±0.79% (90 runs sampled)
Fastest is EventEmitter3(master)

Starting benchmark emit-multiple-listeners.js

EventEmitter1 x 2,507,915 ops/sec ±0.53% (93 runs sampled)
EventEmitter2 x 1,126,907 ops/sec ±0.29% (94 runs sampled)
EventEmitter3@0.1.6 x 2,377,802 ops/sec ±0.92% (89 runs sampled)
EventEmitter3(master) x 2,904,038 ops/sec ±1.06% (94 runs sampled)
fastemitter x 2,804,437 ops/sec ±0.30% (92 runs sampled)
event-emitter x 944,055 ops/sec ±0.21% (94 runs sampled)
contra/emitter x 363,577 ops/sec ±0.46% (90 runs sampled)
Fastest is EventEmitter3(master)

Starting benchmark context.js

EventEmitter1 x 5,944,004 ops/sec ±0.40% (92 runs sampled)
EventEmitter2 x 6,142,119 ops/sec ±0.33% (88 runs sampled)
EventEmitter3@0.1.6 x 10,021,281 ops/sec ±0.34% (90 runs sampled)
EventEmitter3(master) x 12,449,276 ops/sec ±0.85% (87 runs sampled)
Drip x 6,112,535 ops/sec ±1.07% (94 runs sampled)
fastemitter x 5,351,583 ops/sec ±0.33% (91 runs sampled)
event-emitter x 4,664,745 ops/sec ±0.89% (91 runs sampled)
contra/emitter x 432,819 ops/sec ±0.45% (93 runs sampled)
Fastest is EventEmitter3(master)

Starting benchmark once.js

EventEmitter1 x 3,570,512 ops/sec ±0.43% (90 runs sampled)
EventEmitter2 x 2,375,433 ops/sec ±1.28% (88 runs sampled)
EventEmitter3@0.1.6 x 6,800,263 ops/sec ±0.62% (89 runs sampled)
EventEmitter3(master) x 11,971,608 ops/sec ±1.55% (86 runs sampled)
Drip x 6,555,088 ops/sec ±0.80% (87 runs sampled)
fastemitter x 6,320,868 ops/sec ±0.41% (87 runs sampled)
event-emitter x 2,251,961 ops/sec ±0.26% (90 runs sampled)
contra/emitter x 1,373,169 ops/sec ±0.36% (94 runs sampled)
Fastest is EventEmitter3(master)

Starting benchmark hundreds.js

EventEmitter1 x 376,475 ops/sec ±0.32% (89 runs sampled)
EventEmitter2 x 163,023 ops/sec ±0.30% (94 runs sampled)
EventEmitter3@0.1.6 x 342,899 ops/sec ±0.32% (93 runs sampled)
EventEmitter3(master) x 343,984 ops/sec ±0.31% (93 runs sampled)
Drip x 323,076 ops/sec ±0.29% (90 runs sampled)
fastemitter x 435,626 ops/sec ±0.32% (90 runs sampled)
event-emitter x 169,640 ops/sec ±0.40% (90 runs sampled)
contra/emitter x 94,023 ops/sec ±0.45% (90 runs sampled)
Fastest is fastemitter

Starting benchmark emit.js

EventEmitter1 x 6,174,178 ops/sec ±0.28% (93 runs sampled)
EventEmitter2 x 6,334,281 ops/sec ±0.72% (94 runs sampled)
EventEmitter3@0.1.6 x 10,379,672 ops/sec ±0.38% (90 runs sampled)
EventEmitter3(master) x 12,147,337 ops/sec ±0.54% (84 runs sampled)
Drip x 6,290,746 ops/sec ±0.30% (93 runs sampled)
fastemitter x 5,301,900 ops/sec ±0.72% (92 runs sampled)
event-emitter x 4,887,035 ops/sec ±0.43% (89 runs sampled)
contra/emitter x 427,013 ops/sec ±0.76% (93 runs sampled)
Fastest is EventEmitter3(master)

Starting benchmark add-remove.js

EventEmitter1 x 4,737,119 ops/sec ±0.32% (91 runs sampled)
EventEmitter2 x 4,775,450 ops/sec ±0.56% (88 runs sampled)
EventEmitter3@0.1.6 x 7,598,665 ops/sec ±0.52% (91 runs sampled)
EventEmitter3(master) x 18,016,994 ops/sec ±0.43% (87 runs sampled)
Drip x 32,917,832 ops/sec ±1.55% (82 runs sampled)
fastemitter x 15,904,236 ops/sec ±0.40% (88 runs sampled)
event-emitter x 3,809,036 ops/sec ±0.75% (93 runs sampled)
contra/emitter x 6,141,581 ops/sec ±0.33% (93 runs sampled)
Fastest is Drip
```

**Pull request merged**
