### PR TITLE
Allow for `once` to return a promise

### PR DESCRIPTION
**Pull request by benjamingr**
To start some discussion regarding https://github.com/nodejs/node/pull/20909#issuecomment-391380789

### CODE REVIEW

**Comment by lpinca** [comment]
I'm not a fan of this, apart from the simplified usage offered by `await`, what is the real benefit?
cc: @3rd-Eden

**Comment by 3rd-Eden** [comment]
I've been following the discussion around this, and while I applaud the effort modernize the EventEmitter pattern to become fully async aware I don't think that this is way to go about it. It is weird, that a single method of the EventEmitter is upgraded to support async, especially if this be solved in userland in 5~ LOC as well:

```js
function wonce(emitter, event) {
  return new Promise(function (resolve) {
    emitter.once(event, resolve)
  })
}

const data = await wonce(server, 'connected');
```

So for me this, the particular change would be -1, unless Node.js decides to implement it, then we will add support for it as well. Id be much more interested to see if we can make a fully async aware EventEmitter, instead of just spicing up a single method. Maybe work can be done around async iterators/generators for the `on` method. e.g:

```js
for await (const data = stream.on('data')) {
  ...
}
```

Or otherways to make EventEmitter fully async, instead of just a single method.

**Comment by benjamingr** [comment]
> especially if this be solved in userland in 5~ LOC as well:

The reason I am proposing this is because I've seen this seemingly simple implementation done wrong several times - when people have to write `new Promise` they end up having to put logic there.

What do you think about my example here: https://github.com/nodejs/node/pull/20909#issuecomment-391418762 and the discussion here: https://github.com/nodejs/node/pull/20909#issuecomment-391447760 ?

> Maybe work can be done around async iterators/generators for the on method. e.g:

Node.js 10 already ships with `Symbol.asyncIterator` for streams - you can `for await` streams in Node.js _today_. If this excites you - [we need help](https://github.com/nodejs/readable-stream/issues/333)!

**Comment by lpinca** [comment]
I'm closing this, but we should add https://nodejs.org/api/events.html#events_events_once_emitter_name.

**Pull request closed without merging**
