### PR TITLE
allow event name to be an ES6 Symbol

### PR DESCRIPTION
**Pull request by deepsweet**
because now it fails with `Uncaught TypeError: Cannot convert a Symbol value to a string`.

[ES6 Symbols reference](http://www.2ality.com/2014/12/es6-symbols.html).

### CODE REVIEW

**Comment by 3rd-Eden** [comment]
I think it would make more sense to inline this instead of using a function call so there is less performance overhead.

**Comment by deepsweet** [comment]
no problem. I'll squash and rebase if everything is ok for you now.

**Comment by 3rd-Eden** [comment]
LGTM.

**Comment by deepsweet** [comment]
nice.
could you please publish new version? we are stucked with `@0.1.6` because of this.

**Comment by 3rd-Eden** [comment]
Gotta write a test against this before I'm going to release a new version. But that should be done in like 5-10 min

**Comment by 3rd-Eden** [comment]
Published a new version which includes these changes.

**Pull request merged**
